# Generated by Django 3.2.18 on 2023-04-28 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230429_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='count',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='books',
        ),
        migrations.AddField(
            model_name='cart',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='api.book'),
            preserve_default=False,
        ),
    ]
