# Generated by Django 3.2.18 on 2023-05-02 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_order_destination_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.useraddress'),
        ),
    ]
