# Generated by Django 3.2.18 on 2023-05-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20230502_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=0, upload_to='media/books'),
            preserve_default=False,
        ),
    ]
