# Generated by Django 3.2.18 on 2023-05-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230505_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookimage',
            name='image_path',
        ),
        migrations.AddField(
            model_name='bookimage',
            name='image_url',
            field=models.ImageField(default=0, upload_to='books'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
