# Generated by Django 3.2.18 on 2023-05-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20230505_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=0, upload_to='books'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
