# Generated by Django 3.2.18 on 2023-05-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20230505_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookImage',
        ),
    ]
